### ISSUE TITLE
There is a new fork for k8s/autoscalers that again does support pod selectors w/o targetRef

### ISSUE THREAD

**Issue by sker65** [RayBB/airflow-vpa#1]
Hi there, I tried to reimplement the old functionality to specify pod to monitor in the recommender by simply using a selector with matchLabels (no expressions so far).

The fork is https://github.com/sker65/autoscaler (early stage, but the recommender seems to work. Instead of specifying a targetRef in the VPA def you simply:

```
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: foo-vpa
spec:
  selector:
    matchLabels:
      app: foo
...
```
This way it is quite easy to include arbitrary labeled pods not matter whether they were created by a known controller or airflow etc.
